version: '3'

services:

  db:
    image: mysql:5.7
    container_name: cakedb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super2adm1n
      MYSQL_DATABASE: cake_db
      MYSQL_USER: cake_user
      MYSQL_PASSWORD: c2kepHp
    ports:
      - 3306:3306
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      - back

  php:
    build:
      context: ./php-fpm/
    container_name: php
    restart: always
    volumes:
      - ./app/:/var/www/html/
    depends_on:
      - db
    links:
      - db
    networks:
      - back

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    restart: always
    volumes:
      - ./app/:/var/www/html/
    depends_on:
      - php
      - db
    links:
      - php
    ports:
      - 80:80
    networks:
      - back
      - front

networks:
  back:
    driver: "bridge"
  front:
    driver: "bridge"